---
- name: Deploy AWS infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: Deploy Infrastructure
      ansible.builtin.import_role:
        name: infrastructure

- name: Ensure VMs are up-to-date
  hosts: aap
  gather_facts: true
  become: true
  tasks:
    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
