---
- name: Create VPC
  block:
    - name: Create VPC
      amazon.aws.ec2_vpc_net:
        name: "aap-infrastructure-{{ deployment_id }}-vpc"
        cidr_block: "{{ infrastructure_vpc_cidr }}"
        purge_tags: false
        region: "{{ infrastructure_region }}"
        state: present
        tags:
          Name: "aap-infrastructure-{{ deployment_id }}-vpc"
          purpose: ansible-automation-platform
          environment: aap
          deployment: "aap-infrastructure-{{ deployment_id }}"
      register: infrastructure_vpc
      tags:
        - network

    - name: Save VPC id
      ansible.builtin.set_fact:
        infrastructure_vpc_id: "{{ infrastructure_vpc.vpc.id }}"
      when: infrastructure_vpc is defined
      tags:
        - network

- name: Create subnets
  block:
    - name: Create subnets
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ infrastructure_vpc_id }}"
        cidr: "{{ item.cidr }}"
        region: "{{ infrastructure_region }}"
        az: "{{ item.az }}"
        state: present
        tags:
          Name: "aap-infrastructure-{{ deployment_id }}-subnet-{{ item.name }}"
          purpose: ansible-automation-platform
          environment: aap
          deployment: "aap-infrastructure-{{ deployment_id }}"
      loop: "{{ infrastructure_vpc_subnets }}"
      register: infrastructure_subnets
      tags:
        - network

    - name: Save subnet ids
      ansible.builtin.set_fact:
        infrastructure_subnet_ids: "{{ infrastructure_subnets.results | map(attribute='subnet.id') | list }}"
      when: infrastructure_subnets is defined
      tags:
        - network

- name: Create new Internet Gateway
  when: infrastructure_igw_id is not defined
  block:
    - name: Create igw
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ infrastructure_vpc_id }}"
        region: "{{ infrastructure_region }}"
        state: present
        tags:
          Name: "aap-infrastructure-{{ deployment_id }}-igw"
          purpose: ansible-automation-platform
          environment: aap
          deployment: "aap-infrastructure-{{ deployment_id }}"
      register: infrastructure_igw
      tags:
        - network

    - name: Save igw
      ansible.builtin.set_fact:
        infrastructure_igw_id: "{{ infrastructure_igw.gateway_id }}"
      when: infrastructure_igw is defined
      tags:
        - network

- name: Create new security group
  when: infrastructure_security_group_id is not defined
  block:
    - name: Create security group
      amazon.aws.ec2_security_group:
        name: "aap-infrastructure-{{ deployment_id }}-sg"
        description: AAP security group
        vpc_id: "{{ infrastructure_vpc_id }}"
        region: "{{ infrastructure_region }}"
        rules:
          - proto: tcp
            ports:
              - 22
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 22
          - proto: icmp
            icmp_type: 3
            icmp_code: 1
            cidr_ip: "{{ infrastructure_vpc_cidr }}"
            rule_desc: allow ping on local net
          - proto: tcp
            ports:
              - 5432
            cidr_ip: "{{ infrastructure_vpc_cidr }}"
            rule_desc: allow postgresql on local net
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all outbound
        tags:
          Name: "aap-infrastructure-{{ deployment_id }}-sg"
          purpose: ansible-automation-platform
          environment: aap
          deployment: "aap-infrastructure-{{ deployment_id }}"
      register: infrastructure_security_group
      tags:
        - network

    - name: Save security group id
      ansible.builtin.set_fact:
        infrastructure_security_group_id: "{{ infrastructure_security_group.group_id }}"
      when:
        - infrastructure_security_group is defined
      tags:
        - network

- name: Create new route table
  when: infrastructure_route_table_id is not defined
  block:
    - name: Create route table info
      amazon.aws.ec2_vpc_route_table:
        region: "{{ infrastructure_region }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ infrastructure_igw_id }}"
        vpc_id: "{{ infrastructure_vpc_id }}"
        subnets: "{{ infrastructure_subnet_ids }}"
        tags:
          Name: "aap-infrastructure-{{ deployment_id }}-rt"
          purpose: ansible-automation-platform
          environment: aap
          deployment: "aap-infrastructure-{{ deployment_id }}"
      register: infrastructure_route_table
      tags:
        - network

    - name: Save route table id
      ansible.builtin.set_fact:
        infrastructure_route_table_id: "{{ infrastructure_route_table.route_table.id }}"
      when:
        - infrastructure_route_table is defined
      tags:
        - network
