---
- name: Set persistent tags
  ansible.builtin.set_fact:
    persistent_tags:
      purpose: automation
      environment: ansible-automation-platform
      deployment: "aap-infrastructure-{{ deployment_id }}"
  tags:
    - tags
    - ami
    - network
    - database
    - controller
    - hub
    - eda

- name: Merge persistent tags with user defined tags
  ansible.builtin.set_fact:
    infrastructure_tags: "{{ infrastructure_tags | combine(persistent_tags) }}"
  tags:
    - tags
    - ami
    - network
    - database
    - controller
    - hub
    - eda
