---
# Infrastructure Defaults
infrastructure_region: us-east-1
infrastructure_tags: []

# Networking
infrastructure_vpc_cidr: 172.16.0.0/22
infrastructure_vpc_subnets:
  - name: controller
    cidr: 172.16.0.0/24
    az: us-east-1a
  - name: execution
    cidr: 172.16.1.0/24
    az: us-east-1b
  - name: hub
    cidr: 172.16.2.0/24
    az: us-east-1c
  - name: eda
    cidr: 172.16.3.0/24
    az: us-east-1d

# Compute
infrastructure_assign_public_ip: true
infrastructure_delete_on_termination: true

infrastructure_ami_filter:
  architecture: x86_64
  owner-id: "309956199498"
  name: "RHEL-9.2.*_HVM-*"

infrastructure_volumes:
  - device_name: /dev/sda1
    ebs:
      volume_type: io1
      volume_size: 100
      iops: 1500
      delete_on_termination: true

infrastructure_create_controller_lb: false
infrastructure_lb_scheme: internet-facing

infrastructure_controller_instances: 1
infrastructure_controller_shape: m5a.xlarge

infrastructure_execution_instances: 0
infrastructure_execution_shape: m5a.xlarge

infrastructure_hub_instances: 1
infrastructure_hub_shape: m5a.large

infrastructure_eda_instances: 0
infrastructure_eda_shape: m5a.xlarge

# Database
infrastructure_db_username: ansible
infrastructure_db_password: changeme

infrastructure_controller_db_engine_version: "13.12"
infrastructure_controller_db_allow_major_version_upgrade: false
infrastructure_controller_db_auto_minor_version_upgrade: true
infrastructure_controller_db_multi_az: false
infrastructure_controller_db_storage_encrypted: true
infrastructure_controller_db_db_instance_class: db.m5d.xlarge
infrastructure_controller_db_storage_type: io1
infrastructure_controller_db_storage_iops: 1500
infrastructure_controller_db_allocated_storage: 100

infrastructure_hub_db_engine_version: "13.12"
infrastructure_hub_db_allow_major_version_upgrade: false
infrastructure_hub_db_auto_minor_version_upgrade: true
infrastructure_hub_db_multi_az: false
infrastructure_hub_db_storage_encrypted: true
infrastructure_hub_db_db_instance_class: db.m5d.large
infrastructure_hub_db_storage_type: io1
infrastructure_hub_db_storage_iops: 1500
infrastructure_hub_db_allocated_storage: 100

infrastructure_eda_db_engine_version: "13.12"
infrastructure_eda_db_allow_major_version_upgrade: false
infrastructure_eda_db_auto_minor_version_upgrade: true
infrastructure_eda_db_multi_az: false
infrastructure_eda_db_storage_encrypted: true
infrastructure_eda_db_db_instance_class: db.m5d.xlarge
infrastructure_eda_db_storage_type: io1
infrastructure_eda_db_storage_iops: 1500
infrastructure_eda_db_allocated_storage: 100
