---
- name: Run the AAP install script
  ansible.builtin.shell: "ANSIBLE_BECOME_METHOD='sudo' ANSIBLE_BECOME=True {{ aap_installer_installer_path }}setup.sh"
  register: install
  failed_when: install.rc == 1
