---
- name: Notify about time
  ansible.builtin.debug:
    msg: "This process can take a long time to complete.  If you want to follow the logs of the installer, then SSH into the installer server and follow the setup.log file in the `/var/log/tower` directory."

- name: Run the AAP install script
  ansible.builtin.shell: "ANSIBLE_BECOME_METHOD='sudo' ANSIBLE_BECOME=True {{ aap_installer_installer_path }}setup.sh"
  register: install
  failed_when: install.rc == 1
