---
- name: Unarchive installer
  ansible.builtin.import_tasks: unarchive_installer.yml

- name: Create inventory
  ansible.builtin.import_tasks: create_inventory.yml

- name: Configure SSH
  ansible.builtin.import_tasks: configure_ssh.yml

- name: Run the AAP installer
  ansible.builtin.import_tasks: aap_setup.yml
  when: aap_run_installer

- name: Run the AAP installer
  ansible.builtin.import_tasks: post_install_cleanup.yml
  when:
    - aap_run_installer
    - aap_remove_installer_after_install
    - install.rc != 1
