---
- name: Remove installer
  ansible.builtin.file:
    path: "{{ aap_installer_path }}"
    state: absent

- name: Remove SSH key
  ansible.builtin.file:
    path: "{{ aap_installer_ssh_key_dest }}"
    state: absent
