---
- name: Deploy AWS infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: Deploy Infrastructure
      ansible.builtin.include_role:
        name: lab.aws_deployment.infrastructure

    - name: Wait 10 mins for all VMs to become available
      ansible.builtin.wait_for:
        host: "{{ item }}"
        port: 22
        timeout: 600
      loop: "{{ groups.public }}"

- name: Ensure VMs are up-to-date
  hosts: public
  gather_facts: true
  become: true
  tasks:
    - name: Register subscription manager
      community.general.redhat_subscription:
        state: present
        username: "{{ aap_red_hat_username }}"
        password: "{{ aap_red_hat_password }}"
        auto_attach: true

    - name: Ensure rhsm is managing repos
      ansible.builtin.command: sudo subscription-manager config --rhsm.manage_repos=1
      register: rhsp
      failed_when: rhsp.rc == 1

    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

- name: Install AAP
  hosts: installer
  gather_facts: false
  become: false
  vars:
    aap_controller_hosts: "{{ groups.controller_private }}"
    aap_ee_hosts: "{{ groups.execution_private | default('') }}"
    aap_hub_hosts: "{{ groups.hub_private | default('') }}"
    aap_eda_hosts: "{{ groups.eda_private | default('') }}"
    aap_eda_allowed_hostnames: "{{ (groups.eda_public | default([])) | join(',') }}"
    aap_controller_db_host: "{{ hostvars.localhost.infrastructure_controller_db.endpoint.address }}"
    aap_hub_db_host: "{{ hostvars.localhost.infrastructure_hub_db.endpoint.address | default('') }}"
    aap_eda_db_host: "{{ hostvars.localhost.infrastructure_eda_db.endpoint.address | default('') }}"
  tasks:
    - name: Run AAP role
      ansible.builtin.include_role:
        name: lab.aws_deployment.aap
