---
name: Validation CI

"on":
  push:
    branches:
      - main
  pull_request:
    types:
      - assigned
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review
      - review_requested

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install requirements
        run: pip3 install pre-commit ansible

      - name: Install requirements
        run: ansible-galaxy collection install -r requirements.yml

      - name: Run pre-commit tests
        run: pre-commit run -v --all-files
